[package]
name = "tauri-app"
version = "1.0.0"
description = "EPUB Shelf — Tauri protótipo"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["dialog-all", "shell-open"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
